# Generated by Django 2.2.6 on 2019-10-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191015_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone_num',
            new_name='phone_number',
        ),
    ]
