# Generated by Django 2.2.6 on 2019-10-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_product_manufacturer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
